name: GitHub-Profile-3D-Contrib

on:
  schedule:
    # Runs at the top of every hour (UTC)
    - cron: "0 * * * *"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    name: GitHub-Profile-3D-Contrib
    steps:
      - uses: actions/checkout@v3
      - uses: yoshi389111/github-profile-3d-contrib@0.7.1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          USERNAME: ${{ github.repository_owner }}
      - name: Commit & Push
        run: |
          git config user.name LeoShangTang
          git config user.email leoshang12@gmail.com
          git add -A .
          git commit -m "generated"
          git push